idade = 0
input("digite seu nome:")
input("digite sua idade:")
input("você deseja tirar sua carteira de abilitação?")
input("Você ja fez o exame de vista?")
input("Você ja fez o exame psicotécnico:") 
input("Você ja fez o cursinho teorico?")
input("Você ja fez as aulas praticas?")
print("Parabens sua carteira de motorista chega em duas semanas!!!")
print("")